version: '3.7'
services:
  webserver:
    image: puckel/docker-airflow:1.10.9
    restart: always
    environment:
      - LOAD_EX=n
#      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////data/db/airflow.db
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./pipelines:/usr/local/airflow/dags
      - ./requirements.txt:/requirements.txt
#      - ./db:/data/db
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
