version: '3.7'
services:

  webserver:
    build:
      dockerfile: dockerfiles/airflow.Dockerfile
      context: .
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./pipelines:/usr/local/airflow/dags
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
